# Generated by Django 5.1.6 on 2025-02-13 07:15

from django.db import migrations
from ..models import OrderStatuses, Order


def load_data(apps, schema_editor):
    """Загрузка тестовых данных"""
    Order = apps.get_model('orders_manager', 'Order')
    Item = apps.get_model('orders_manager', 'Item')
    OrderItem = apps.get_model('orders_manager', 'OrderItem')

    pizza = Item.objects.create(dish="Пицца", price=10.50)
    pasta = Item.objects.create(dish="Карбонара", price=12.00)
    salad = Item.objects.create(dish="Салат Цезарь", price=8.50)

    order1 = Order.objects.create(table_number=5, status=OrderStatuses.WAITING)
    order2 = Order.objects.create(table_number=3, status=OrderStatuses.READY)

    OrderItem.objects.create(order=order1, item=pizza, quantity=2)
    OrderItem.objects.create(order=order1, item=salad, quantity=1)
    OrderItem.objects.create(order=order2, item=pasta, quantity=1)


class Migration(migrations.Migration):

    dependencies = [
        ('orders_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
